### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by ek** [jshcrowthe/polymer-angular-demo#1]
Hello,

I would like to copy the code in [polymer-events.html](https://github.com/jshcrowthe/polymer-angular-demo/blob/master/polymer-events.html) for commercial usage. Can you add a license (MIT?) so that I may properly attribute and use the code snippet?

Best regards,
Eric

**Comment by jshcrowthe** [comment]
@ek Sure! I will get something put in.

**Comment by jshcrowthe** [comment]
Closed in 3f3de30ab730ae30a95c5e9217d549cceebf866d
