### ISSUE TITLE
notify event not fire: the syntax of property-name-changed is wrong

### ISSUE THREAD

**Issue by oishiimendesu** [jshcrowthe/polymer-angular-demo#2]
in https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#property-notification:

The event type follows a naming convention of property-changed, **where property’s mixedCase words are written with dashes**. E.g. a **change to  this.firstName will fire first-name-changed**. Listeners will receive an event object whose e.detail.value attribute has the changing property’s new value.

in polymer-events.html
you have to do a change (line 41):

 compile: function bindPolymerCompile(el, attr) {
          var attrMap = {};
          for (var prop in attr) {
            if (angular.isString(attr[prop])) {
              var _match = attr[prop].match(/{{\s_([.\w]+)\s_}}/);
              if (_match) {
           *\*     attrMap[prop] = $parse(_match[1]);**
              }
            }
          }

change: **attrMap[prop]** = $parse(_match[1]); 
TO 
**attrMap[attr.$attr[prop]]** = $parse(_match[1]);

**Comment by jshcrowthe** [comment]
@menorless Great catch! I will get the demo updated!
